name: "Set up OGD dependencies"
author: Luke Swanson
description: "Given a game and a date range, this action will export the range's data for that game."
branding:
  icon: 'download'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Set up local bin in path # there is a warning about this in pip output, so we'll do this and see if that makes things better.
      run: export PATH=/home/runner/.local/bin:$PATH
      shell: bash
    - name: Get correct Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.x"
    - name: Set up pip
      run: |
        python3.10 -m pip install --upgrade pip
      shell: bash
    - name: Set up Python libraries
      # if: steps.cache.outputs.cache-hit != 'true'
      run: |
        python3.10 -m pip install setuptools --quiet
        python3.10 -m pip install wheel --quiet
        python3.10 -m pip install -r requirements.txt --quiet
      shell: bash