# Workflow to build and test the APIUtils project
name: CI Script - APIUtils
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/CI_APIUtils.yml'
    - '.github/workflows/BUILD_APIUtils.yml'
    - '.github/workflows/DEPLOY_APIUtils.yml'
    - '.github/actions/**'
    - 'requirements.txt'
    - 'src/**'
    - 'tests/utils/**'

jobs:

  setup:
    name: Get Branch
    runs-on: ubuntu-24.04
    outputs:
      branch-tag: ${{ steps.get-branch.outputs.branch-name }}
    steps:
      - name: Get Branch
        id: get-branch
        uses: opengamedata/actions-get-branch@v1.0

  testbed_server_config:
    name: ServerConfig Testbed
    uses: ./.github/workflows/TEST_ServerConfig.yml

  testbed_api_response:
    name: APIResponse Testbed
    uses: ./.github/workflows/TEST_APIResponse.yml

  testbed_api_utils:
    name: APIUtils Testbed
    uses: ./.github/workflows/TEST_APIUtils.yml

  testbed_hello_local:
    name: HelloAPI Local Testbed
    uses: ./.github/workflows/TEST_resources_local.yml

  build:
    name: Build Python Package
    needs: [setup, testbed_hello_local, testbed_server_config, testbed_api_response, testbed_api_utils]
    uses: ./.github/workflows/BUILD_APIUtils.yml
    with:
      image_name:   ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:    ${{ needs.setup.outputs.branch-tag }}
      with_caching: false
    secrets:
      image_repository: ${{ secrets.DOCKER_IMAGE_REPO }}
  
  deploy_helloapi:
    name: CI Deploy to GCP
    needs: [setup, testbed_hello_local, testbed_server_config, testbed_api_response, testbed_api_utils, build]
    uses: ./.github/workflows/DEPLOY_APIUtils.yml
    with:
      image_name: ${{ github.repository }} # github.repository includes organization as prefix
      image_tag:  ${{ needs.setup.outputs.branch-tag }}
      remove: false
    secrets: inherit

  testbed_hello_remote:
    name: HelloAPI Remote Testbed
    needs: deploy_helloapi
    uses: ./.github/workflows/TEST_resources_remote.yml
