# Workflow to build and deploy a new release of OGDUtils to PyPi.
name: OGD APIUtils - CI Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/APIUtils_CI.yml'
    - '.github/actions/**'
    - 'src/**'
    - 'requirements.txt'

jobs:
  build:
    name: Build Package for Release
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Get Dependencies
      uses: ./.github/actions/install_dependencies
    - name: Build Package
      run: python -m build

  testbed_server_config_schema:
    name: ServerConfigSchema Testbed
    needs: build
    uses: ./.github/workflows/TEST_ServerConfigSchema.yml


  run_testbed_hello:
    name: Run HelloAPI Testbed
    needs: build
    uses: ./.github/workflows/TEST_HelloAPI.yml

  testbed_api_response:
    name: APIResponse Testbed
    needs: build
    uses: ./.github/workflows/TEST_APIResponse.yml

  run_testbed_api_utils:
    name: Run APIUtils Testbed
    needs: build
    uses: ./.github/workflows/TEST_APIUtils.yml
