# Workflow to build and deploy a new release of OGDUtils to PyPi.
name: OGD APIUtils - CI Script
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/APIUtils_CI.yml'
    - '.github/actions/**'
    - 'src/**'
    - 'requirements.txt'

jobs:

  build:
    name: Build Python Package
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    steps:
    - uses: actions/checkout@v3
    - name: Get Dependencies
      uses: opengamedata/setup-ogd-py-dependencies@v1.0
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Build Package
      run: python -m build

  testbed_server_config_schema:
    name: ServerConfigSchema Testbed
    needs: build
    uses: ./.github/workflows/TEST_ServerConfigSchema.yml

  testbed_hello:
    name: HelloAPI Testbed
    needs: build
    uses: ./.github/workflows/TEST_HelloAPI.yml

  testbed_api_response:
    name: APIResponse Testbed
    needs: build
    uses: ./.github/workflows/TEST_APIResponse.yml

  testbed_api_utils:
    name: APIUtils Testbed
    needs: build
    uses: ./.github/workflows/TEST_APIUtils.yml
