# Workflow to clean out the directory where files from a deleted "APIUtils" branch were deployed on the CI server
name: Cleanup Dead Branch - APIUtils
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'delete' && github.event.ref || 'Manual Run') }}

on:
  delete: # Trigger automatically when we do a deletion of a branch
  workflow_dispatch:
    
jobs:
  branch_delete:
    name: Remove Deploy of Deleted Branch
    if: github.event.ref_type == 'branch'
    uses: ./.github/workflows/DEPLOY_APIUtils.yml
    with:
      branch: ${{ github.ref_name }}
      remove: true
    secrets: inherit
    