# Workflow to clean out the directory where files from a deleted "APIUtils" branch were deployed on the CI server
name: Cleanup Dead Branch - APIUtils
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'delete' && github.event.ref || 'Manual Run') }}

on:
  delete: # Trigger automatically when we do a deletion of a branch
  workflow_dispatch:
    
jobs:
  setup:
    name: Get Branch
    runs-on: ubuntu-24.04
    outputs:
      branch_tag: ${{ steps.get_branch.outputs.branch-name }}
    steps:
      - name: Get Branch
        id: get_branch
        uses: opengamedata/actions-get-branch@v1.1
        with:
          n: 20
          remove: '\\.'

  branch_delete:
    name: Dead Branch Cleanup
    if: github.event.ref_type == 'branch'
    needs: [setup]
    uses: ./.github/workflows/DEPLOY_APIUtils.yml
    with:
      image_name: "N/A"
      revision_tag: ${{ needs.setup.outputs.branch_tag }}
      remove: true
    secrets: inherit
    