# Workflow to test Files API on the CI server
name: OGD APIUtils - ServerConfigSchema Testbed
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
  workflow_call:
  push:
    paths:
    - '.github/workflows/APIUtils_test_ServerConfigSchema.yml'
    - '.github/actions/test_config/**'
    - 'tests/cases/schemas/t_ServerConfigSchema.py'
    - 'tests/config/**'
    - 'requirements.txt'

jobs:

  run_testbed_server_config_schema:
    name: Run ServerConfigSchema Testbed
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-ServerConfigSchema
      cancel-in-progress: true

    steps:
  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Get Dependencies
      uses: opengamedata/setup-ogd-py-dependencies@v1.0
      with:
        python_version: ${{ vars.OGD_PYTHON_VERSION }}
    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          verbose_output: "True"

  # 2. Build & configure remote environments

  # 3. Perform export
    - name: Execute testbed
      run: python -m unittest ./tests/cases/schemas/t_ServerConfigSchema.py 

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        path: ./*.log
