# Workflow to test the Hello API on the CI server
name: Remote Testbed - HelloAPI resources
run-name: ${{ format('{0} - {1}', github.workflow, github.event_name == 'push' && github.event.head_commit.message || 'Manual Run') }}
on:
  workflow_dispatch:
    inputs:
      base_url:
        type: string
        description: "The base URL of the deploy to test."
        required: true
  workflow_call:
    inputs:
      base_url:
        type: string
        description: "The base URL of the deploy to test."
        required: true
  # push:
  #   paths:
  #   - '.github/workflows/TEST_resources_remote.yml'
  #   - '.github/actions/test_config/**'
  #   - 'tests/cases/resources/**/RemoteCase.py'
  #   - 'tests/config/**'
  #   - '!.github/workflows/CI_APIUtils.yml'
  #   - '!.github/workflows/BUILD_APIUtils.yml'
  #   - '!.github/actions/**'
  #   - '!requirements.txt'
  #   - '!src/**'
  #   - '!tests/utils/**'

jobs:
  check_deploy:
    name: Check for Existing Deploy
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true
    
    steps:
    - name: cURL Check Hello Endpoint
      run: curl -Is --fail-with-body https://${{ inputs.base_url }}/hello

  run_testbed_hello_remote:
    name: Run HelloAPI Remote Testbed
    needs: [check_deploy]
    # if: always() && (needs.check_deploy.result == 'success' || needs.deploy_if_needed.result == 'success')
    if: always() && needs.check_deploy.result == 'success'
    runs-on: ubuntu-24.04
    container: python:${{ vars.OGD_PYTHON_VERSION }}-alpine
    defaults:
      run:
        shell: sh
    concurrency:
      group: ${{ github.repository }}-${{ github.ref }}-${{ github.workflow }}-HelloAPI-remote
      cancel-in-progress: true

    steps:

    - name: Announce testing
      run: echo "Testing HelloAPI endpoint at ${{ inputs.base_url }}"

  # 1. Local checkout 
    - name: Checkout repository
      uses: actions/checkout@v7.0.1
    - name: Get Dependencies
      run: python -m pip install -r requirements.txt
    - name: Local self-install
      run: python -m pip install -e .

    - name: Set up Config File
      uses: ./.github/actions/test_config
      with:
          remote_url: ${{ inputs.base_url }}
          verbose_output: "True"
          shell: sh

  # 2. Build & configure remote environments

  # 3. Perform tests
    - name: Execute testbed
      run: python -m unittest discover -s tests/cases/resources/ -p "RemoteCase.py" -t ./

  # 4. Cleanup & complete
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v7.0.1
      with:
        name: "test-log"
        path: ./*.log
